### ISSUE TITLE
Segfault under heavy load

### ISSUE THREAD

**Issue by raistmaj** [OlafvdSpek/ctemplate#115]
Hi,

We are using ctemplate in our products, after some internal test, the library is segfaulting always around the same area.

First, this is the code we use to communicate with ctemplate (the area where it crashes):

    m_expandedTemplate.clear();
    ctemplate::TemplateDictionary localDict("localTemplateDict");
    for(std::map<std::string, LocalizableString>::const_iterator it = m_fields.begin(); it != m_fields.end(); ++it) {
    	localDict[it->first] = it->second.toString(0);	// TODO
    }
    std::string path = "/companyname.templatelib/" + m_appName + "/" + m_templateId + "/" + locale();
    std::string lTemplateContent = m_preamble + std::string(m_templateContents->data(),m_templateContents->data()+m_templateContents->length()) + m_postamble;
    if(!ctemplate::StringToTemplateCache(path, lTemplateContent.data(), lTemplateContent.size(), ctemplate::DO_NOT_STRIP)) {
    	m_status = Status(Status::ERROR, "Could not insert the template into the cache.");
    	return;
    }
    if(!ctemplate::ExpandTemplate(path, ctemplate::DO_NOT_STRIP, &localDict, &m_expandedTemplate)){
    	m_status = Status(Status::ERROR, "Could not expand the template.");
    	return;
    }
    ctemplate::mutable_default_template_cache()->Delete(path);

This produces paths in this format = /companyname.templatelib//service/templateid/en. 

GDB report crashes on this lines

#0 ctemplate::Template::state (this=0x96d2a48) at src/template.cc:2335
#1 0x083a517a in StringToTemplateCache (strip=<optimized out>, content_len=<optimized out>, content=<optimized out>, key=..., this=<optimized out>)
at deliver/include/extlibs/ctemplate/template_cache.h:125
#2 StringToTemplateCache (strip=<optimized out>, content_len=<optimized out>, content=<optimized out>, key=...) at deliver/include/extlibs/ctemplate/template.h:156
#3 LocalizedTemplate::expand (this=0xf1dfed00) at src/templatelib/templatelib.cpp:200

The line 200 is StringToTemplateCache, I'm extremely confused because I can't find any reason why is crashing because the cache is mutex protected.

**Comment by raistmaj** [comment]
Well, definitely looks like a race condition, latest dump with a full thread log(I have removed the company code)

(gdb) thread apply all bt

Thread 4 (Thread 0xf15ffb90 (LWP 26185)):
#0  0x083bc902 in std::vector<std::pair<unsigned long long, int>, std::allocator<std::pair<unsigned long long, int> > >::_M_insert_aux (this=0xf15fe910, 
    __position=<error reading variable: Cannot access memory at address 0x0>, __x=...) at /usr/lib/gcc/i386-redhat-linux/4.3.2/../../../../include/c++/4.3.2/bits/vector.tcc:343
#1  0x083ba567 in push_back (__x=..., this=<optimized out>) at /usr/lib/gcc/i386-redhat-linux/4.3.2/../../../../include/c++/4.3.2/bits/stl_vector.h:694
#2  ctemplate::TemplateCache::Delete (this=0x9e16740, key=...) at src/template_cache.cc:600
#3  0x083a6659 in cuda::LocalizedTemplate::expand (this=0xf15fecf8) at src/templatelib/templatelib.cpp:233
#4  0x083a689d in cuda::LocalizedTemplate::toString (this=0xf15fecf8) at src/templatelib/templatelib.cpp:188

....

Thread 1 (Thread 0xf1dffb90 (LWP 26184)):
#0  ctemplate::Template::state (this=0x9e16740) at src/template.cc:2335
#1  0x083a6538 in StringToTemplateCache (strip=<optimized out>, content_len=<optimized out>, content=<optimized out>, key=..., this=<optimized out>)
    at deliver/include/extlibs/ctemplate/template_cache.h:125
#2  StringToTemplateCache (strip=<optimized out>, content_len=<optimized out>, content=<optimized out>, key=...) at deliver/include/extlibs/ctemplate/template.h:156
#3  cuda::LocalizedTemplate::expand (this=0xf1dfecf8) at src/templatelib/templatelib.cpp:223
#4  0x083a689d in cuda::LocalizedTemplate::toString (this=0xf1dfecf8) at src/templatelib/templatelib.cpp:188
